# Generated by Django 5.0.1 on 2024-02-09 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='updates',
        ),
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(default=datetime.datetime(2024, 2, 9, 14, 59, 29, 472576, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
